name: Configure Panorama
# label used for menu selection
label: Configure Panorama on AWS

description: |
  Configure Panorama with optional HA

# type of skillet (panos or panorama or template or terraform)
type: python3

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection:
    - Reference Architecture Skillet Modules

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: AWS_ACCESS_KEY_ID
    description: ID
    default: 
    type_hint: hidden
  - name: AWS_SECRET_ACCESS_KEY
    description: Secret
    default:
    type_hint: hidden
  - name: PASSWORD
    description: Password for the admin account
    default:
    type_hint: hidden
  - name: Panorama_IP
    description: Panorama IP
    default:
    type_hint: hidden
  - name: Secondary_IP
    description: Panorama IP for HA pair
    default:
    type_hint: hidden
  - name: enable_ha
    description: Deploy as a HA Pair
    default:
    type_hint: hidden
  - name: Primary_Serial
    description: Serial Number for the Primary Panorama
    default:
    type_hint: text
  - name: OTP
    description: OTP for the Primary Panorama from the support portal
    default:
    type_hint: text
  - name: Secondary_Serial
    description: Serial Number for the Secondary Panorama
    type_hint: text
    toggle_hint:
      source: enable_ha
      value: 'true' 
  - name: Secondary_OTP
    description: OTP for Second Panorama from the support portal
    type_hint: text
    toggle_hint:
      source: enable_ha
      value: "true"
  - name: Primary_Private_IP
    description: Private or Internal IP
    default:
    type_hint: hidden
  - name: Secondary_Private_IP
    description: Private or Internal IP
    default:
    type_hint: hidden

snippets:
  - name: script
    file: configure_panorama.py
    input_type: env


