---
- name: Panorama OTP
  hosts: primary-panorama
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Authorize plugin with OTP
    panos_op: 
      provider:
        ip_address: '{{ ip_address }}'
        password: '{{ password }}'
      cmd: "{{'request plugins cloud_services panorama-certificate fetch otp ' + primary_otp }}"
    register: result
    failed_when: result.stdout.find("Failure")